extends: stylelint-config-standard
rules:
    string-quotes: double
    no-duplicate-selectors: true
    color-hex-case: lower
    color-hex-length: long
    selector-attribute-quotes: always
    declaration-colon-space-before: never
    property-no-vendor-prefix: true
    value-no-vendor-prefix: true
    number-leading-zero: always
    function-url-quotes: always
    at-rule-no-vendor-prefix: true
    selector-no-vendor-prefix: true
    media-feature-name-no-vendor-prefix: true
