---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: hugo/content/_singular
  label: " singular"
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/careers
  label: Careers
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/company
  label: Company
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/dev_blog
  label: Dev blog
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/privacy
  label: Privacy
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/products
  label: Products
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/resources
  label: Resources
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/tools
  label: Tools
  create: all
  match: "**/*"
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: hugo/data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: hugo/static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.31.1
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.31.1
  preview_output_directory: public
  output_directory: public
version: 0.31.1
